# Generated by Django 5.1.1 on 2024-09-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='form',
        ),
        migrations.RemoveField(
            model_name='responsefield',
            name='form_field',
        ),
        migrations.AddField(
            model_name='response',
            name='form_field',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='forms.formfield'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsefield',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_fields', to='forms.response'),
        ),
    ]
