# Generated by Django 5.1.1 on 2024-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_response_form_remove_responsefield_form_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsefield',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
